import { createFileRoute } from "@tanstack/react-router";
import { ArrowRight, Image, Layers3, ScanSearch } from "lucide-react";
import { ProjectDetail } from "@/components/project-detail";

export const Route = createFileRoute("/projects/computer-vision-suite")({ head: () => ({ meta: [
  { title: "Computer Vision Suite — Sahil Ahire" }, { name: "description", content: "Architecture and outcomes from ESRGAN, Pix2Pix, and CNN computer vision pipelines." }, { property: "og:title", content: "Advanced Computer Vision Suite" }, { property: "og:description", content: "Generative vision systems for super-resolution, translation, and colorization." }, { property: "og:type", content: "article" }, { name: "twitter:card", content: "summary_large_image" },
], links: [{ rel: "canonical", href: "/projects/computer-vision-suite" }] }), component: VisionPage });
function Pipeline(){const stages=[{name:"Super-resolution",model:"ESRGAN",desc:"Reconstructs high-frequency detail from low-resolution inputs.",I:ScanSearch},{name:"Image translation",model:"Pix2Pix",desc:"Learns paired mappings between visual domains with a conditional GAN.",I:Layers3},{name:"Colorization",model:"CNN",desc:"Predicts plausible chrominance from grayscale luminance context.",I:Image}];return <section className="rounded-md border border-border bg-card/60 p-5 sm:p-7"><p className="font-mono text-xs text-primary">VISION MODEL MATRIX</p><h2 className="mt-1 font-semibold">Three pipelines, one research suite</h2><div className="mt-6 space-y-3">{stages.map(({name,model,desc,I},i)=><div key={name} className="grid gap-4 rounded-md border border-border bg-background/55 p-4 sm:grid-cols-[auto_1fr_auto] sm:items-center"><span className="grid size-11 place-items-center rounded-md bg-accent/10 text-accent"><I size={20}/></span><div><div className="flex items-center gap-2"><h3 className="font-semibold">{name}</h3><span className="font-mono text-[10px] text-primary">{model}</span></div><p className="mt-1 text-sm leading-6 text-muted-foreground">{desc}</p></div>{i<2&&<ArrowRight className="hidden text-muted-foreground sm:block" size={17}/>}</div>)}</div></section>}
function VisionPage(){return <ProjectDetail number="03" title="Advanced Computer Vision Suite" eyebrow="Generative vision" summary="A collection of deep learning pipelines exploring how machines can reconstruct, translate, and color visual information." stack={["ESRGAN","Pix2Pix","CNN","TensorFlow","OpenCV"]} problem="Visual restoration tasks demand different objectives and model architectures despite sharing a pixel-based input domain. This suite compares adversarial and convolutional approaches across resolution enhancement, paired image translation, and grayscale colorization in a unified experimentation workflow." results={[{value:"3",label:"Vision pipelines"},{value:"ESRGAN",label:"Super-resolution"},{value:"Pix2Pix",label:"Translation"},{value:"CNN",label:"Colorization"}]} architecture={[{label:"Prepare",detail:"Build paired and task-specific datasets with deterministic transforms and splits."},{label:"Train",detail:"Optimize specialized generator, discriminator, or CNN objectives per visual task."},{label:"Validate",detail:"Compare perceptual quality and reconstruction behavior on unseen samples."},{label:"Serve",detail:"Wrap consistent preprocessing and inference interfaces around each trained model."}]} nextTo="/projects/lawbot" nextLabel="LawBot"><Pipeline/></ProjectDetail>}
