/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsEsrganRouteImport } from './routes/projects.esrgan'
import { Route as ProjectsImageColorizationRouteImport } from './routes/projects.image-colorization'
import { Route as ProjectsLawbotRouteImport } from './routes/projects.lawbot'
import { Route as ProjectsSmartContractDetectionRouteImport } from './routes/projects.smart-contract-detection'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsEsrganRoute = ProjectsEsrganRouteImport.update({
  id: '/projects/esrgan',
  path: '/projects/esrgan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsImageColorizationRoute =
  ProjectsImageColorizationRouteImport.update({
    id: '/projects/image-colorization',
    path: '/projects/image-colorization',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsLawbotRoute = ProjectsLawbotRouteImport.update({
  id: '/projects/lawbot',
  path: '/projects/lawbot',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSmartContractDetectionRoute =
  ProjectsSmartContractDetectionRouteImport.update({
    id: '/projects/smart-contract-detection',
    path: '/projects/smart-contract-detection',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/esrgan': typeof ProjectsEsrganRoute
  '/projects/image-colorization': typeof ProjectsImageColorizationRoute
  '/projects/lawbot': typeof ProjectsLawbotRoute
  '/projects/smart-contract-detection': typeof ProjectsSmartContractDetectionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects/esrgan': typeof ProjectsEsrganRoute
  '/projects/image-colorization': typeof ProjectsImageColorizationRoute
  '/projects/lawbot': typeof ProjectsLawbotRoute
  '/projects/smart-contract-detection': typeof ProjectsSmartContractDetectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/esrgan': typeof ProjectsEsrganRoute
  '/projects/image-colorization': typeof ProjectsImageColorizationRoute
  '/projects/lawbot': typeof ProjectsLawbotRoute
  '/projects/smart-contract-detection': typeof ProjectsSmartContractDetectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects/esrgan'
    | '/projects/image-colorization'
    | '/projects/lawbot'
    | '/projects/smart-contract-detection'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects/esrgan'
    | '/projects/image-colorization'
    | '/projects/lawbot'
    | '/projects/smart-contract-detection'
  id:
    | '__root__'
    | '/'
    | '/projects/esrgan'
    | '/projects/image-colorization'
    | '/projects/lawbot'
    | '/projects/smart-contract-detection'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsEsrganRoute: typeof ProjectsEsrganRoute
  ProjectsImageColorizationRoute: typeof ProjectsImageColorizationRoute
  ProjectsLawbotRoute: typeof ProjectsLawbotRoute
  ProjectsSmartContractDetectionRoute: typeof ProjectsSmartContractDetectionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/esrgan': {
      id: '/projects/esrgan'
      path: '/projects/esrgan'
      fullPath: '/projects/esrgan'
      preLoaderRoute: typeof ProjectsEsrganRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/image-colorization': {
      id: '/projects/image-colorization'
      path: '/projects/image-colorization'
      fullPath: '/projects/image-colorization'
      preLoaderRoute: typeof ProjectsImageColorizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/lawbot': {
      id: '/projects/lawbot'
      path: '/projects/lawbot'
      fullPath: '/projects/lawbot'
      preLoaderRoute: typeof ProjectsLawbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/smart-contract-detection': {
      id: '/projects/smart-contract-detection'
      path: '/projects/smart-contract-detection'
      fullPath: '/projects/smart-contract-detection'
      preLoaderRoute: typeof ProjectsSmartContractDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsEsrganRoute: ProjectsEsrganRoute,
  ProjectsImageColorizationRoute: ProjectsImageColorizationRoute,
  ProjectsLawbotRoute: ProjectsLawbotRoute,
  ProjectsSmartContractDetectionRoute: ProjectsSmartContractDetectionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
